apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deploy
spec:
  template:
    spec:
      containers:
        - name: springapp-deploy
          image: 992382409375.dkr.ecr.ap-northeast-2.amazonaws.com/footprints:main-b2ab27876b4f46cd42e362e08f184e42caf4dd3c-dev
