apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deploy
spec:
  template:
    spec:
      containers:
        - name: springapp-deploy
          imagePullPolicy: Always
          image: 992382409375.dkr.ecr.ap-northeast-2.amazonaws.com/footprints:main-d89823a53890846c74426aaa61d5f1554c968946-prod