apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: springapp-deploy
  template:
    metadata:
      labels:
        app: springapp-deploy
    spec:
      containers:
        - name: springapp-deploy
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"