apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: springapp
commonLabels:
  app: springapp-pod

images:
  - name: springapp-pod

resources:
  - ./deployment.yaml
  - ./service.yaml