apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deploy
spec:
  selector:
    matchLabels:
      app: springapp-pod
  template:
    metadata:
      labels:
        app: springapp-pod
    spec:
      containers:
        - name: springapp-container
          imagePullPolicy: Always
          image: 992382409375.dkr.ecr.ap-northeast-2.amazonaws.com/footprints:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: springapp-svc
spec:
  selector:
    app: springapp-pod
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
